server:
  port: 8080

spring:
  profiles:
    include: core

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration


app:
  global:
    enable: false
    limit-time-section: 10
    limit-count: 2
    priority: 1
  user:
    enable: true
    limit-time-section: 10    # 시간구간
    limit-count: 5           # 접속제한횟수
    priority: 2
    limit-urls:
      - /request-limit/dl
      - /request-limit/info