
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: com.mooop.m.config.CustomDialect
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/KMVC_DB?useSSL=false&allowPublicKeyRetrieval=true
      username: cwkim
      password: cwkim1234
      driver-class-name: com.mysql.cj.jdbc.Driver