
spring:
  profiles:
    include: core
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/KMVC_DB?useSSL=false&allowPublicKeyRetrieval=true
      username: cwkim
      password: cwkim1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    check-template-location: true
    template-resolver-order: 0
  mvc:
    static-path-pattern: /resources/**

logging:
  level:
    org.springframework.security: DEBUG

